<a href="https://colab.research.google.com/github/istanranjith175b-commits/Exploring-datasets/blob/main/exp5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
data = {'weight': [60, 65, 70, 75, 80, 85, 90, 95, 100, 105],
        'bins': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C']}
df = pd.DataFrame(data)
display(df)
bins = [50, 70, 90, 110]
labels = ['Light', 'Medium', 'Heavy']

df['weight_category'] = pd.cut(df['weight'], bins=bins, labels=labels)
display(df)
pd.value_counts(df['weight_category'])

   weight bins
0      60    A
1      65    B
2      70    A
3      75    C
4      80    B
5      85    A
6      90    C
7      95    B
8     100    A
9     105    C

   weight bins weight_category
0      60    A           Light
1      65    B           Light
2      70    A           Light
3      75    C          Medium
4      80    B          Medium
5      85    A          Medium
6      90    C          Medium
7      95    B           Heavy
8     100    A           Heavy
9     105    C           Heavy

/tmp/ipykernel_813/1253492771.py:12: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df['weight_category'])

weight_category
Medium    4
Light     3
Heavy     3
Name: count, dtype: int64

In [16]:
rn = np.random.rand(2000)
rn
category2=pd.qcut(rn,4)
category2
pd.value_counts(category2)

/tmp/ipykernel_813/3908646153.py:5: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category2)

(-8.100000000000002e-05, 0.252]    500
(0.252, 0.499]                     500
(0.499, 0.764]                     500
(0.764, 1.0]                       500
Name: count, dtype: int64