<a href="https://colab.research.google.com/github/istanranjith175b-commits/Exploring-datasets/blob/main/missingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Recreate this dataset in Python
data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [28.0, np.nan, 35.0, 42.0, 29.0],
    'Department': ['HR', 'IT', None, 'Marketing', 'Sales'],
    'Join_Date': ['2023-01-15', '2022-06-12', '2021-11-01', np.nan, '2024-02-20'],
    'Salary': [55000.0, 72000.0, 85000.0, np.nan, 60000.0]
}

df = pd.DataFrame(data)

   Employee_ID     Name   Age Department   Join_Date   Salary
0          101    Alice  28.0         HR  2023-01-15  55000.0
1          102      Bob   NaN         IT  2022-06-12  72000.0
2          103  Charlie  35.0       None  2021-11-01  85000.0
3          104    David  42.0  Marketing         NaN      NaN
4          105      Eva  29.0      Sales  2024-02-20  60000.0

In [5]:
ecommerce_data = {
    'Product_ID': ['P01', 'P02', 'P03', 'P04', 'P05'],
    'Category': ['Electronics', 'Clothing', None, 'Home', 'Electronics'],
    'Price': [799.99, 29.99, 49.99, np.nan, 120.00],
    'Rating': [4.5, np.nan, 3.8, 4.2, 4.9],
    'Discount_%': [10.0, 0.0, np.nan, 15.0, np.nan],
    'Stock_Status': ['In Stock', 'Out of Stock', 'In Stock', None, 'In Stock']
}

dfx= pd.DataFrame(ecommerce_data)

df_horizontal = pd.concat([df, df_store], axis=1)
print(df_horizontal)

   Employee_ID     Name   Age Department   Join_Date   Salary Product_ID  \
0          101    Alice  28.0         HR  2023-01-15  55000.0        P01
1          102      Bob   NaN         IT  2022-06-12  72000.0        P02
2          103  Charlie  35.0       None  2021-11-01  85000.0        P03
3          104    David  42.0  Marketing         NaN      NaN        P04
4          105      Eva  29.0      Sales  2024-02-20  60000.0        P05

      Category   Price  Rating  Discount_%  Stock_Status
0  Electronics  799.99     4.5        10.0      In Stock
1     Clothing   29.99     NaN         0.0  Out of Stock
2         None   49.99     3.8         NaN      In Stock
3         Home     NaN     4.2        15.0          None
4  Electronics  120.00     4.9         NaN      In Stock

In [7]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            1
Department     1
Join_Date      1
Salary         1
dtype: int64

In [9]:
dfx.isnull().sum()

Product_ID      0
Category        1
Price           1
Rating          1
Discount_%      2
Stock_Status    1
dtype: int64

In [10]:
dfx.notnull()

   Product_ID  Category  Price  Rating  Discount_%  Stock_Status
0        True      True   True    True        True          True
1        True      True   True   False        True          True
2        True     False   True    True       False          True
3        True      True  False    True        True         False
4        True      True   True    True       False          True

In [13]:
df.dropna()

   Employee_ID   Name   Age Department   Join_Date   Salary
0          101  Alice  28.0         HR  2023-01-15  55000.0
4          105    Eva  29.0      Sales  2024-02-20  60000.0

In [14]:
dfx.dropna()

  Product_ID     Category   Price  Rating  Discount_% Stock_Status
0        P01  Electronics  799.99     4.5        10.0     In Stock

In [15]:
df.count()

Employee_ID    5
Name           5
Age            4
Department     4
Join_Date      4
Salary         4
dtype: int64

In [21]:
dfx.dropna(how="all")

  Product_ID     Category   Price  Rating  Discount_%  Stock_Status
0        P01  Electronics  799.99     4.5        10.0      In Stock
1        P02     Clothing   29.99     NaN         0.0  Out of Stock
2        P03         None   49.99     3.8         NaN      In Stock
3        P04         Home     NaN     4.2        15.0          None
4        P05  Electronics  120.00     4.9         NaN      In Stock

In [34]:
dfx.ffill()

  Product_ID     Category   Price  Rating  Discount_%  Stock_Status
0        P01  Electronics  799.99     4.5        10.0      In Stock
1        P02     Clothing   29.99     4.5         0.0  Out of Stock
2        P03     Clothing   49.99     3.8         0.0      In Stock
3        P04         Home   49.99     4.2        15.0      In Stock
4        P05  Electronics  120.00     4.9        15.0      In Stock

In [35]:
dfx.bfill()

  Product_ID     Category   Price  Rating  Discount_%  Stock_Status
0        P01  Electronics  799.99     4.5        10.0      In Stock
1        P02     Clothing   29.99     3.8         0.0  Out of Stock
2        P03         Home   49.99     3.8        15.0      In Stock
3        P04         Home  120.00     4.2        15.0      In Stock
4        P05  Electronics  120.00     4.9         NaN      In Stock

In [36]:
df.dropna(how='all')

   Employee_ID     Name   Age Department   Join_Date   Salary
0          101    Alice  28.0         HR  2023-01-15  55000.0
1          102      Bob   NaN         IT  2022-06-12  72000.0
2          103  Charlie  35.0       None  2021-11-01  85000.0
3          104    David  42.0  Marketing         NaN      NaN
4          105      Eva  29.0      Sales  2024-02-20  60000.0

In [37]:
df.dropna(how='all',axis=1)

   Employee_ID     Name   Age Department   Join_Date   Salary
0          101    Alice  28.0         HR  2023-01-15  55000.0
1          102      Bob   NaN         IT  2022-06-12  72000.0
2          103  Charlie  35.0       None  2021-11-01  85000.0
3          104    David  42.0  Marketing         NaN      NaN
4          105      Eva  29.0      Sales  2024-02-20  60000.0

In [38]:
df.dropna(how='all',axis=0)

   Employee_ID     Name   Age Department   Join_Date   Salary
0          101    Alice  28.0         HR  2023-01-15  55000.0
1          102      Bob   NaN         IT  2022-06-12  72000.0
2          103  Charlie  35.0       None  2021-11-01  85000.0
3          104    David  42.0  Marketing         NaN      NaN
4          105      Eva  29.0      Sales  2024-02-20  60000.0